{...}: {
  # Generated by `nixos-generate-config`, wrapped as a flake-parts module.
  # Re-running the generator writes a plain NixOS module — re-wrap it, don't
  # drop the generated body straight into modules/.
  flake.nixosModules.antonHardware = {
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/3bdd65ce-e639-4901-ac59-da3fa4db97db";
      fsType = "ext4";
    };

    # Dedicated NixOS ESP (nvme0n1p5, "NIXOS-BOOT"). The original 200M ESP
    # (70CF-316E, nvme0n1p1) is left to Windows and deliberately not mounted.
    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/0C92-4ED6";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.npu.enable = true;
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
